name: Publish
on: release
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: actions/setup-node@master
      with:
        node-version: 10
    - name: Publish to npm
      if: github.event.action == 'created'
      run: |
        echo "registry=https://registry.npmjs.org/" > ~/.npmrc
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
        yarn publish --tag latest --access public
      env:
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}